app:
  name: my_project
  env: dev
  port: 8081

db:
  dsn: postgres://postgres:123456@127.0.0.1:5432/my_project?sslmode=disable
  max_open_conns: 25
  max_idle_conns: 5

queue:
  max_workers: 10
  poll_time: 5
  job_timeout: 10
  max_attempts: 5

cache:
  addr: localhost:6379
  password: ""
  db: 0

ai:
  retry:
  endpoints:
    - name: openai
      models:
        - openai
      config:
        api_key: xxx
        base_url: https://xxx
